version: "3.7"

volumes:
  vol_shared:
    external: true
    name: volume_swarm_shared
  vol_certificates:
    external: true
    name: volume_swarm_certificates

networks:
  network_public:
    external: true
    name: network_swarm_public
  network_private:
    external: true
    name: network_swarm_private

services:
  reverse_proxy:
    image: traefik:v2.1.1 # The official Treafik docker image
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
      resources:
        limits:
          memory: 512M
      restart_policy:
        condition: on-failure
        delay: 11s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./files/traefik-conf:/etc/traefik"
    ports:
      - "80:80" # The HTTP port
      - "443:443" # The HTTPS port
      - "8080:8080" # The Web UI (Enabled by --api)
    networks:
      - network_public

  whoami:
    image: containous/whoami
    depends_on:
      - reverse_proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.swarm.localhost`)"
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"
      resources:
        limits:
          memory: 256M
      restart_policy:
        condition: on-failure
        delay: 10s
      mode: replicated
      replicas: 2
    networks:
      - network_public
